<template><div><h1 id="数据库结构" tabindex="-1"><a class="header-anchor" href="#数据库结构" aria-hidden="true">#</a> 数据库结构</h1>
<ul>
<li>id 为预留字段（关联表除外），本框架不使用，可以根据不同业务需要采用不同的 id 生成策略算法；</li>
<li>只有两种状态的字段（互斥状态），默认 0 统一都是正常状态；</li>
<li>数据库的时间字段使用不带时区的 timestamp 类型</li>
</ul>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>PostgreSQL 如果没有设置主键，那么会默认以 <code v-pre>id</code> 、类型为整数（integer）的列作为主键，该字段并不显示。</p>
</div>
<h2 id="一、表字段" tabindex="-1"><a class="header-anchor" href="#一、表字段" aria-hidden="true">#</a> 一、表字段</h2>
<h3 id="_1-通用字段" tabindex="-1"><a class="header-anchor" href="#_1-通用字段" aria-hidden="true">#</a> 1. 通用字段</h3>
<p>除关联表以外的其它表基本都含有这几个字段，不过也应视具体情况而定。</p>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>创建者</td>
<td>create_by</td>
<td>varchar(64)</td>
<td>createBy</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>更新者</td>
<td>update_by</td>
<td>varchar(64)</td>
<td>updateBy</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>创建时间</td>
<td>create_time</td>
<td>timestamp</td>
<td>createTime</td>
<td>LocalDateTime</td>
<td></td>
</tr>
<tr>
<td>更新时间</td>
<td>update_time</td>
<td>timestamp</td>
<td>updateTime</td>
<td>LocalDateTime</td>
<td></td>
</tr>
<tr>
<td>备注</td>
<td>remark</td>
<td>varchar(255)</td>
<td>remark</td>
<td>String</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_2-用户登录信息表-leaf-user" tabindex="-1"><a class="header-anchor" href="#_2-用户登录信息表-leaf-user" aria-hidden="true">#</a> 2. 用户登录信息表（leaf_user）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>userID</td>
<td>user_id</td>
<td>int8</td>
<td>userId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>账号</td>
<td>username</td>
<td>varchar(32)</td>
<td>username</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>密码</td>
<td>password</td>
<td>varchar(32)</td>
<td>password</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>手机号</td>
<td>phone</td>
<td>char(11)</td>
<td>phone</td>
<td>String</td>
<td>绑定手机号</td>
</tr>
<tr>
<td>邮箱</td>
<td>email</td>
<td>varchar(64)</td>
<td>email</td>
<td>String</td>
<td>绑定邮箱</td>
</tr>
<tr>
<td>头像地址</td>
<td>avatar</td>
<td>varchar(64)</td>
<td>avatar</td>
<td>String</td>
<td>图片地址</td>
</tr>
<tr>
<td>昵称</td>
<td>nick_name</td>
<td>varchar(64)</td>
<td>nickName</td>
<td>String</td>
<td>用户昵称</td>
</tr>
<tr>
<td>用户信息id</td>
<td>user_detail_id</td>
<td>int8</td>
<td>userDetailId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>状态</td>
<td>status</td>
<td>int2</td>
<td>status</td>
<td>Integer</td>
<td>状态：1正常，0禁用</td>
</tr>
<tr>
<td>删除标志</td>
<td>del_flag</td>
<td>int2</td>
<td>delFlag</td>
<td>Integer</td>
<td>1已删除，0未删除</td>
</tr>
</tbody>
</table>
<h3 id="_3-用户信息详情表-leaf-user-detail" tabindex="-1"><a class="header-anchor" href="#_3-用户信息详情表-leaf-user-detail" aria-hidden="true">#</a> 3. 用户信息详情表（leaf_user_detail）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>user_detail_id</td>
<td>user_detail_id</td>
<td>int8</td>
<td>userDetailId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>用户编码</td>
<td>user_code</td>
<td>varchar(64)</td>
<td>userCode</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>所属部门id</td>
<td>dept_id</td>
<td>int8</td>
<td>deptId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>姓氏</td>
<td>first_name</td>
<td>varchar(64)</td>
<td>firstName</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>名称</td>
<td>last_name</td>
<td>varchar(64)</td>
<td>lastName</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>全名</td>
<td>full_name</td>
<td>varchar(64)</td>
<td>fullName</td>
<td>String</td>
<td>全名</td>
</tr>
<tr>
<td>民族</td>
<td>ethnic</td>
<td>varchar(32)</td>
<td>ethnic</td>
<td>String</td>
<td>民族</td>
</tr>
<tr>
<td>联系电话</td>
<td>mobile</td>
<td>varchar(11)</td>
<td>mobile</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>性别</td>
<td>gender</td>
<td>int2</td>
<td>gender</td>
<td>String</td>
<td>0 保密，1 女，2 男</td>
</tr>
<tr>
<td>年龄</td>
<td>age</td>
<td>int2</td>
<td>age</td>
<td>Integer</td>
<td>人生七十古来稀</td>
</tr>
<tr>
<td>住址</td>
<td>address</td>
<td>varchar(200)</td>
<td>address</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>故乡</td>
<td>hometown</td>
<td>varchar(200)</td>
<td>hometown</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>身份证号</td>
<td>id_card</td>
<td>varchar(18)</td>
<td>idCard</td>
<td>String</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_4-角色表-leaf-role" tabindex="-1"><a class="header-anchor" href="#_4-角色表-leaf-role" aria-hidden="true">#</a> 4. 角色表（leaf_role）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>roleID</td>
<td>role_id</td>
<td>int8</td>
<td>roleId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>角色名称</td>
<td>role_name</td>
<td>varchar(20)</td>
<td>roleName</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>角色编码</td>
<td>role_code</td>
<td>varchar(20)</td>
<td>roleCode</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>状态</td>
<td>status</td>
<td>int2</td>
<td>status</td>
<td>Integer</td>
<td>1正常，0禁用</td>
</tr>
<tr>
<td>删除标志</td>
<td>del_flag</td>
<td>int2</td>
<td>delFlag</td>
<td>Integer</td>
<td>1已删除，0未删除</td>
</tr>
</tbody>
</table>
<h3 id="_5-用户-角色关联表-leaf-user-role" tabindex="-1"><a class="header-anchor" href="#_5-用户-角色关联表-leaf-user-role" aria-hidden="true">#</a> 5. 用户-角色关联表（leaf_user_role）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>id</td>
<td>id</td>
<td>int8</td>
<td>id</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>用户ID</td>
<td>user_id</td>
<td>int8</td>
<td>userId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>角色ID</td>
<td>role_id</td>
<td>int8</td>
<td>roleId</td>
<td>Long</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_6-部门表-leaf-dept" tabindex="-1"><a class="header-anchor" href="#_6-部门表-leaf-dept" aria-hidden="true">#</a> 6. 部门表（leaf_dept）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>实体字段</th>
<th>实体类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>deptID</td>
<td>dept_id</td>
<td>int8</td>
<td>deptId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>父级部门id</td>
<td>parent_id</td>
<td>int8</td>
<td>parent_Id</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>部门编码</td>
<td>dept_code</td>
<td>varchar(20)</td>
<td>deptCode</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>部门名称</td>
<td>dept_name</td>
<td>varchar(20)</td>
<td>deptName</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>部门负责人id</td>
<td>leader_id</td>
<td>int8</td>
<td>leaderId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>部门描述</td>
<td>description</td>
<td>varchar(255)</td>
<td>description</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>状态</td>
<td>status</td>
<td>int2</td>
<td>status</td>
<td>Integer</td>
<td>1正常，0禁用</td>
</tr>
<tr>
<td>删除标志</td>
<td>del_flag</td>
<td>int2</td>
<td>delFlag</td>
<td>Integer</td>
<td>1已删除，0未删除</td>
</tr>
</tbody>
</table>
<h3 id="_7-部门-角色关联表-leaf-dept-role" tabindex="-1"><a class="header-anchor" href="#_7-部门-角色关联表-leaf-dept-role" aria-hidden="true">#</a> 7. 部门-角色关联表（leaf_dept_role）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>Java字段</th>
<th>Java类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>id</td>
<td>id</td>
<td>int8</td>
<td>id</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>部门ID</td>
<td>dept_id</td>
<td>int8</td>
<td>deptId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>角色ID</td>
<td>role_id</td>
<td>int8</td>
<td>roleId</td>
<td>Long</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_8-字典表-leaf-dict" tabindex="-1"><a class="header-anchor" href="#_8-字典表-leaf-dict" aria-hidden="true">#</a> 8. 字典表（leaf_dict）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>实体字段</th>
<th>实体类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>dictID</td>
<td>dict_id</td>
<td>int8</td>
<td>dictId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>字典键</td>
<td>dict_key</td>
<td>varchar(20)</td>
<td>dictKey</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>字典值</td>
<td>dict_value</td>
<td>varchar(20)</td>
<td>dictValue</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>字典类型</td>
<td>dict_type</td>
<td>varchar(20)</td>
<td>dictType</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>状态</td>
<td>status</td>
<td>int2</td>
<td>status</td>
<td>Integer</td>
<td>1正常，0禁用</td>
</tr>
<tr>
<td>删除标志</td>
<td>del_flag</td>
<td>int2</td>
<td>delFlag</td>
<td>Integer</td>
<td>1已删除，0未删除</td>
</tr>
</tbody>
</table>
<h3 id="_9-角色-菜单关联表-leaf-menu-role" tabindex="-1"><a class="header-anchor" href="#_9-角色-菜单关联表-leaf-menu-role" aria-hidden="true">#</a> 9. 角色-菜单关联表（leaf_menu_role）</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>实体字段</th>
<th>实体类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>id</td>
<td>id</td>
<td>int8</td>
<td>id</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>角色id</td>
<td>role_id</td>
<td>int8</td>
<td>roleId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>菜单id</td>
<td>menu_id</td>
<td>int8</td>
<td>menu_id</td>
<td>Long</td>
<td></td>
</tr>
</tbody>
</table>
<h3 id="_10-菜单表-leaf-menu" tabindex="-1"><a class="header-anchor" href="#_10-菜单表-leaf-menu" aria-hidden="true">#</a> 10. 菜单表（leaf_menu)</h3>
<table>
<thead>
<tr>
<th>名称</th>
<th>数据库字段</th>
<th>数据库类型</th>
<th>实体字段</th>
<th>实体类型</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>menuID</td>
<td>menu_id</td>
<td>int8</td>
<td>menuId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>菜单名称</td>
<td>menu_name</td>
<td>varchar(20)</td>
<td>menuName</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>菜单类型</td>
<td>menu_type</td>
<td>char</td>
<td>menuType</td>
<td>String</td>
<td>菜单类型：D目录，M菜单，B按钮</td>
</tr>
<tr>
<td>菜单图标</td>
<td>icon_url</td>
<td>varchar(20)</td>
<td>iconUrl</td>
<td>String</td>
<td></td>
</tr>
<tr>
<td>父级菜单id</td>
<td>parent_id</td>
<td>int8</td>
<td>parentId</td>
<td>Long</td>
<td></td>
</tr>
<tr>
<td>显示顺序</td>
<td>order_num</td>
<td>int4</td>
<td>orderNum</td>
<td>Integer</td>
<td>菜单显示顺序</td>
</tr>
<tr>
<td>层次</td>
<td>level</td>
<td>int2</td>
<td>level</td>
<td>Integer</td>
<td></td>
</tr>
<tr>
<td>权限字符</td>
<td>permission</td>
<td>varchar(20)</td>
<td>permission</td>
<td>String</td>
<td>菜单显示顺序</td>
</tr>
<tr>
<td>是否隐藏</td>
<td>hide</td>
<td>int2</td>
<td>hide</td>
<td>Integer</td>
<td>0显示，1隐藏，</td>
</tr>
<tr>
<td>状态</td>
<td>status</td>
<td>int2</td>
<td>status</td>
<td>Integer</td>
<td>0未删除，1正常，</td>
</tr>
</tbody>
</table>
<h2 id="二、说明" tabindex="-1"><a class="header-anchor" href="#二、说明" aria-hidden="true">#</a> 二、说明</h2>
<p>用户的账号和用户的信息分开，在账户表中使用 <code v-pre>detail_id</code> 进行关联，这样维护信息、代码虽然比较麻烦，但是用户信息比较安全，后续扩展也比较方便。</p>
<p>虽说小公司或者说刚起步的业务用户数量不多，存在一起比较方便，但是还是推荐这种方式，这也是浪子问 ChatGPT
之后才知道账号信息和用户信息分开这种方式的。</p>
</div></template>


