quarkus:
  log:
    category:
      "com.leaf.system.resource": ERROR
    console:
      level: ALL
      # color
      darken: 5
    file:
      encoding: UTF-8
      path: ./log/app.log
    handler:
      file:
        "com.leaf.system.resource":
          level: error