quarkus:
  http:
    port: 8001
  datasource:
    master:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/leaf_main
      username: postgres
      password: postgres
    slave1:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: postgres
