quarkus:
  http:
    port: 7777
  datasource:
    master:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/test
        driver:
        max-size: 16
      username: postgres
      password: postgres
    slave:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/test
        driver:
        max-size: 16
      username: postgres
      password: postgres
  jimmer:
    show-sql: true
    pretty-sql: true
    database-validation:
      mode: none

