quarkus:
  http:
    port: 7777
  datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/leaf_main
        driver:
        max-size: 16
      username: postgres
      password: postgres
  jimmer:
    show-sql: true
    pretty-sql: true
    database-validation:
      mode: none

platform:
  quarkus:
    native:
      builder-image: false
