############################# 端口号 #############################
server:
  port: 7777

############################# Spring 相关 #############################
spring:
  application:
    # 应用名称
    name: leaf-example-boot3
  # SpringBoot 2.x 版本是 servlet，2.x 之前是 http
  servlet:
    multipart:
      # 一次请求中单个文件最大大小
      max-file-size: 10MB
      # 一次请求所有文件大小的和
      max-request-size: 20MB
  # 数据源
  datasource:
    # hikari 连接池
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/leaf_master?serverTimezone=Asia/Shanghai
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
      # 空闲连接超时时间
      idle-timeout: 60000
      # 连接超时时间
      connection-timeout: 60000
      # 最大连接池
      maximum-pool-size: 10
  # jpa 配置
  jpa:
    # 显示 SQL
    show-sql: true
    open-in-view: false
    # generate-ddl: true
    hibernate:
      # 命名策略
      naming:
        # 相当于 org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy（3.0删除）
        # 驼峰与下划线映射
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    # jpa 属性配置
    properties:
      hibernate:
        # 格式化控制台打印的 SQL
        format_sql: true

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      database: 0
#      username:
#      password:


# Spring 日志级别，默认为 info 级别
logging:
  level:
    # 指定 repository 包内的日志级别
    com.leaf.repository: debug
    # SQL 语句显示参数
    org.hibernate.stat: debug
    org.hibernate.sql: debug

############################# 项目自定义配置 #############################
leaf:
  # version
  version: v1.0.0
  api-prefix: api
