quarkus:
  http:
    port: 8000
  datasource:
    - name: master
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/leaf_main
      username: postgres
      password: postgres
    - name: slave
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: postgres

  jimmer:
    show-sql: true
    pretty-sql: true
    database-validation:
      mode: none