############################# 端口号 #############################
server:
  port: 7777
############################# Spring 相关 #############################
spring:
  application:
    # 应用名称
    name: leaf
  # SpringBoot 2.x 版本是 servlet，2.x 之前是 http
  servlet:
    multipart:
      # 一次请求中单个文件最大大小
      max-file-size: 10MB
      # 一次请求所有文件大小的和
      max-request-size: 20MB
  # 数据源
  datasource:
    ds1:
      # hikari 连接池
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/leaf_main?serverTimezone=Asia/Shanghai
      username: postgres
      password: postgres
      hikari:
        auto-commit: true
        # 空闲连接超时时间
        idle-timeout: 60000
        # 连接超时时间
        connection-timeout: 60000
        # 最大连接池
        maximum-pool-size: 10
    ds2:
      # hikari 连接池
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/leaf_main?serverTimezone=Asia/Shanghai
      username: postgres
      password: postgres
      hikari:
        auto-commit: true
        # 空闲连接超时时间
        idle-timeout: 60000
        # 连接超时时间
        connection-timeout: 60000
        # 最大连接池
        maximum-pool-size: 10


# jimmer
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  # 假外键
  is-foreign-key-enabled-by-default: false
  # NONE: 不验证数据库结构，这是默认行为。
  # WARNNING: 验证数据库结构，如果数据库结构和实体模型定义不一致，不阻止程序运行，只是在日志中打印告警信息。
  # ERROR: 验证数据库结构，如果数据库结构和实体模型定义不一致，抛出异常，阻止程序运行。
  database-validation:
    mode: error
  client:
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Leaf Open API
          description: Swagger Api
          version: 0.1
    ts:
      path: /ts.zip

# Spring 日志级别，默认为 info 级别
logging:
  level:
    web: debug

############################# 项目自定义配置 #############################
leaf:
  # version
  version: v1.0.0
  api-prefix: api

