quarkus:
  banner:
    path: banner.txt
  http:
    port: 8000

  log:
    level: INFO
    file:
      enable: true
      encoding: UTF-8
      level: debug
      rotation:
        # 文件日期滚动
        file-suffix: .yyyy-MM-dd
        # 文件数滚动
        max-backup-index: 30
        # 是否按服务启动滚动
        rotate-on-boot: false
  # 关闭控制台颜色
  console:
    color: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/leaf_main
    username: postgres
    password: postgres
    # master:
    #   db-kind: postgresql
    #   jdbc:
    #     url: jdbc:postgresql://localhost:5432/leaf_main
    #   username: postgres
    #   password: postgres
    # worker_1:
    #   db-kind: postgresql
    #   jdbc:
    #     url: jdbc:postgresql://localhost:5432/test
    #   username: postgres
    #   password: postgres

# ############################# 项目自定义配置 #############################
leaf:
  version: v1.0.0