[versions]
quarkus = "3.14.4"
jimmer = "0.8.179"
quarkusJimmer = "0.0.1.CR28"
commonLang3 = "3.17.0"
jetbrainAnnotations = "24.1.0"
kotlin = "2.0.20"
guava = "33.3.0-jre"

[libraries]
####################################### Jimmer #######################################
# jimmer apt
jimmer-apt = { module = "org.babyfish.jimmer:jimmer-apt", version.ref = "jimmer" }
# jimmer sql
#jimmer-sql = { module = "org.babyfish.jimmer:jimmer-sql", version.ref = "jimmer" }
# Jimmer 的 Quarkus 扩展
jimmer-quarkus = { module = "io.github.flynndi:quarkus-jimmer", version.ref = "quarkusJimmer" }

####################################### Quarkus #######################################
# quarkus 基础依赖
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-rest = { module = "io.quarkus:quarkus-rest", version.ref = "quarkus" }
# jackson 在 Quarkus 中，只要引入了 json 扩展，默认情况下 Quarkus 将对大多数返回值使用 application/json 媒体类型，除非显式声明
quarkus-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }
# yml 支持
quarkus-yaml = { module = "io.quarkus:quarkus-config-yaml", version.ref = "quarkus" }
# jwt
quarkus-jwt = { module = "io.quarkus:quarkus-smallrye-jwt", version.ref = "quarkus" }
# test
quarkus-junit5 = { module = "org.quarkus:quarkus-junit5", version.ref = "quarkus" }
quarkus-junit5-mockito = { module = "org.quarkus:quarkus-junit5-mockito", version.ref = "quarkus" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "quarkus" }

####################################### database #######################################
# pg jdbc
quarkus-pg = { module = "io.quarkus:quarkus-jdbc-postgresql", version.ref = "quarkus" }
# jbdc 数据源
quarkus-agroal = { module = "io.quarkus:quarkus-agroal", version.ref = "quarkus" }
# 事务
quarkus-jta = { module = "io.quarkus:quarkus-narayana-jta", version.ref = "quarkus" }

####################################### Other #######################################
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonLang3" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainAnnotations" }
# 缩略图
thumbnail = { group = "net.coobird", name = "thumbnailator", version = "0.4.20" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

[bundles]
quarkus = [
    "quarkus-arc",
    "quarkus-jackson",
    "quarkus-yaml",
    "quarkus-jwt",
    "quarkus-pg",
    "quarkus-agroal",
    "quarkus-jta",
]
# https://quarkus.io/guides/getting-started-testing
quarkus-test = [
    "quarkus-junit5",
    "quarkus-junit5-mockito",
    "rest-assured"
]

[plugins]
