[versions]
jimmerVersion = "0.8.134"
lombokVersion = "1.18.34"
springBoot = "3.3.1"
springDenpendencyManagement = "1.1.5"
postgresql = "42.7.3"
commonLang3 = "3.14.0"
jetbrainAnnotations = "24.1.0"
jwtVersion = "4.4.0"
kotlin = "2.0.0"

[libraries]
# apt
jimmer-apt = { module = "org.babyfish.jimmer:jimmer-apt", version.ref = "jimmerVersion" }
# Jimmer Spring Boot Starter
jimmer-spring-boot = { module = "org.babyfish.jimmer:jimmer-spring-boot-starter", version.ref = "jimmerVersion" }

# Spring Boot 相关
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }

# Postgresql
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonLang3" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombokVersion" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainAnnotations" }
jwt = { group = "com.auth0", name = "java-jwt", version.ref = "jwtVersion" }

# 缩略图
thumbnail = { group = "net.coobird", name = "thumbnailator", version = "0.4.19" }

[bundles]
spring = ["spring-boot", "spring-boot-starter-aop", "spring-boot-starter-security", "spring-boot-starter-web"]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
# Spring Boot 官方提供的 Gradle 插件之一，可以帮助开发人员更轻松地管理项目依赖项。统一管理项目依赖项的版本，使项目的依赖项版本更加清晰明确，避免出现依赖冲突。
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDenpendencyManagement" }
