spring:
  application:
    # 应用名称
    name: market-vben-example
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password:
      url: jdbc:mysql://localhost:3306/market_vben?serverTimezone=UTC
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # mysql 用 false | oracle 用 true
      pool-prepared-statements: false
  # redis
  redis:
    host: localhost
    port: 6379
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      naming:
        # 相当于 org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy（3.0删除）
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# 日志
logging:
  level:
    com.market.example.mapper: debug

# controller 请求前加入统一前缀
api:
  path:
    global-prefix: api

token:
  prefix: Bearer